// AUTO-GENERATED by scripts/bundle-dashie-kb.js — DO NOT EDIT.
// Source of truth: js/ai/knowledge/dashie-kb/*.md (format: js/ai/knowledge/README.md).
// A hand-edit here is silently wiped on the next regen; edit the source .md and run:
//   node scripts/bundle-dashie-kb.js
// Gated by lint:dashie-kb (--check). Page IDs validated against the settings registries
// (JS_KOTLIN_CONTRACTS.md #23). `status: hold` chunks are excluded at compile time.

export interface KbChunk {
  id: string;
  file: string;
  title: string;
  topic: 'overview' | 'features' | 'settings' | 'troubleshooting' | 'faq' | 'voice';
  status: 'ga' | 'beta';
  /** Settings page ID the answer refers to (v2 navigate seam; unused in v1). */
  page: string | null;
  /** The action that would perform it, e.g. open_settings_page(<id>) (v2 seam). */
  action: string | null;
  body: string;
}

export const KB_CHUNKS: KbChunk[] = [
  {
    "id": "faq:how-is-dashie-different-from-fully-kiosk-browser",
    "file": "faq.md",
    "title": "How is Dashie different from Fully Kiosk Browser?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie is purpose-built for Home Assistant rather than being a generic kiosk browser. Compared to\nFully Kiosk, Dashie adds a \"Hey Dashie\" voice assistant, a native music overlay, camera/face wake,\nauto-discovery and a URL builder for setup, and a Fully Kiosk–compatible REST API. And you can sign\nin to turn the same app into a full family dashboard — no reinstall."
  },
  {
    "id": "faq:which-calendars-and-photo-sources-are-supported",
    "file": "faq.md",
    "title": "Which calendars and photo sources are supported?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Calendars: Google and Outlook accounts, plus Home Assistant and CalDAV calendars, merged into one\nview. Photos come from several sources — Home Assistant media, a local folder, Immich, Google\nPhotos, Google Drive, and Dropbox — and you can also upload photos straight from your phone (see\n\"How do I add my own photos?\")."
  },
  {
    "id": "faq:can-multiple-family-members-use-it-how-do-roles-work",
    "file": "faq.md",
    "title": "Can multiple family members use it? How do roles work?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Yes. A family has an Owner and can add Parents and Members. Owners and Parents can create and edit\nchores and rewards and see everyone's data; Members complete chores, redeem rewards, and manage\ntheir own profile. All members share the owner's account tier and feature access."
  },
  {
    "id": "faq:does-the-voice-assistant-use-my-data-or-send-it-to-the-web",
    "file": "faq.md",
    "title": "Does the voice assistant use my data or send it to the web?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "For product and how-to questions, Dashie answers from its own built-in knowledge rather than\nsearching the web. Calendar, weather, and smart-home answers come from your connected accounts and\ndevices. Full-mode voice uses a cloud AI provider you choose (Claude, OpenAI, or Gemini); kiosk\nvoice runs through Home Assistant's Assist pipeline. Search queries aren't logged with your\nidentity."
  },
  {
    "id": "faq:what-ai-models-can-i-choose-from",
    "file": "faq.md",
    "title": "What AI models can I choose from?",
    "topic": "faq",
    "status": "ga",
    "page": "voice-ai-model-select",
    "action": "open_settings_page(voice-ai-model-select)",
    "body": "Dashie supports multiple AI providers — Anthropic Claude, OpenAI, and Google Gemini. Pick the one\nyou want under **Settings → Voice & AI → AI model**."
  },
  {
    "id": "faq:does-dashie-work-offline",
    "file": "faq.md",
    "title": "Does Dashie work offline?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Kiosk mode is designed to keep working offline for displaying a local Home Assistant dashboard.\nThe full family dashboard and cloud AI voice features need an internet connection. On-device wake\nword detection works without the cloud. If you'd rather not use cloud voice at all, Dashie can use\nlocal voice engines that run on your own hardware (see \"Can I use local, private voice?\")."
  },
  {
    "id": "faq:can-i-use-local-private-voice",
    "file": "faq.md",
    "title": "Can I use local, private voice?",
    "topic": "faq",
    "status": "beta",
    "page": "voice",
    "action": "open_settings_page(voice)",
    "body": "Newer feature — may not be on your plan yet. In **Settings → Voice & AI** you can choose local\nvoice engines that run on your own devices instead of the cloud — for example local text-to-speech\nand Whisper speech-to-text on your box, or Piper/Whisper through your Home Assistant. Local voice\nis private and doesn't use cloud voice. The available options appear only when Dashie detects a\nsupported engine on your setup."
  },
  {
    "id": "faq:how-do-i-contact-support",
    "file": "faq.md",
    "title": "How do I contact support?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "You can email the Dashie team at **support@dashieapp.com**. On Android you can also send\ndiagnostics from Settings → System to help them look into a problem."
  },
  {
    "id": "faq:what-happens-if-i-delete-my-account",
    "file": "faq.md",
    "title": "What happens if I delete my account?",
    "topic": "faq",
    "status": "beta",
    "page": null,
    "action": null,
    "body": "Newer behavior — may not be on your plan yet. Deleting your account is recoverable for a grace\nperiod (about 15 days): during that window you can change your mind and keep the account before\nanything is permanently removed. Account deletion is managed from your phone or the web console,\nnot from a shared family tablet."
  },
  {
    "id": "faq:what-s-the-difference-between-the-screensaver-photos-and-the",
    "file": "faq.md",
    "title": "What's the difference between the screensaver photos and the Photos widget?",
    "topic": "faq",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "They're configured separately. The **screensaver** slideshow (what shows when the screen is idle)\nis set under Display → Screensaver and can use HA media, a local folder, Immich, or Google Photos.\nThe **Photos widget** (part of the dashboard grid) is set under Settings → Photos and can use\nDropbox albums. You can use different sources for each."
  },
  {
    "id": "features:what-widgets-can-i-put-on-the-dashboard",
    "file": "features.md",
    "title": "What widgets can I put on the dashboard?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "The dashboard is a grid of widgets you can arrange across multiple pages. Available widgets are\nCalendar (upcoming events), Photos (family slideshow), Weather (current conditions, forecast,\nand animated radar), Clock (large digital clock and date), Chores (today's tasks), and Rewards\n(available rewards to redeem). You navigate the grid with a TV remote's D-pad, a keyboard, or\ntouch, and page between layouts with the arrow controls."
  },
  {
    "id": "features:how-does-the-calendar-work",
    "file": "features.md",
    "title": "How does the calendar work?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "The Calendar widget shows your family's upcoming events. It supports multiple Google and Outlook\naccounts, and can merge in calendars from Home Assistant and CalDAV — all deduplicated into one\nview. You choose which of your connected calendars are visible. Ask the assistant things like\n\"what's on the calendar today?\" or \"when is the next soccer game?\" and it reads from your real\nmerged calendar."
  },
  {
    "id": "features:how-do-chores-work",
    "file": "features.md",
    "title": "How do chores work?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Chores are gamified tasks for the family. A parent or owner creates recurring or one-time chores,\neach worth points, and assigns them to a specific member or to \"anyone can complete.\" Chores can\nbe filtered by time of day (morning, afternoon, evening, anytime) and have emoji icons and\ncolors. When someone completes a chore the points are credited automatically. You can mark a\nchore done by voice: \"mark dishes as done.\""
  },
  {
    "id": "features:how-do-rewards-work",
    "file": "features.md",
    "title": "How do rewards work?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Rewards are things family members redeem with the points they earn from chores. A parent sets up\na reward catalog with a point cost for each item, optionally requiring parent approval. When a\nmember redeems a reward, their points are deducted automatically and the redemption is logged."
  },
  {
    "id": "features:how-does-the-photo-screensaver-photos-widget-work",
    "file": "features.md",
    "title": "How does the photo screensaver / photos widget work?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie can show a photo slideshow both as a screensaver and as a dashboard widget. Photo sources\ninclude Home Assistant media, a local folder, Immich, Google Photos, and Dropbox (in full mode).\nYou can control slideshow timing and whether photo metadata (like date or caption) is shown."
  },
  {
    "id": "features:what-can-the-weather-widget-show",
    "file": "features.md",
    "title": "What can the weather widget show?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "The Weather widget shows current conditions, a forecast, and an animated radar map. Weather data\ncomes from Open-Meteo and the radar from RainViewer. By voice you can ask \"what's the weather?\",\n\"will it rain today?\", or \"what's the forecast this weekend?\""
  },
  {
    "id": "features:what-is-the-hey-dashie-voice-assistant",
    "file": "features.md",
    "title": "What is the \"Hey Dashie\" voice assistant?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie includes a hands-free voice assistant activated by saying \"Hey Dashie\" (on supported\ndevices) or by tapping the microphone. It can answer questions about your calendar, the weather,\nand sports; control Home Assistant devices; set timers; complete chores; change the theme; and\nanswer questions about Dashie itself. On the full dashboard it uses cloud AI (Claude, OpenAI, or\nGemini, your choice); kiosk voice runs through Home Assistant's Assist pipeline."
  },
  {
    "id": "features:how-do-timers-work",
    "file": "features.md",
    "title": "How do timers work?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "You can set up to three countdown timers by voice — \"set a 5 minute timer\" — and ask \"how much\ntime is left?\", or pause, resume, and cancel them. Timers show in a small floating overlay and\nplay an alarm when they finish. They survive a page refresh."
  },
  {
    "id": "features:what-can-dashie-do-with-home-assistant",
    "file": "features.md",
    "title": "What can Dashie do with Home Assistant?",
    "topic": "features",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie integrates tightly with Home Assistant. In kiosk mode it displays any HA dashboard\nfull-screen. With voice you can control HA devices — \"turn on the kitchen lights,\" \"close the\ngarage,\" \"is the garage door open?\" — including multi-device commands. Dashie can also sync its\ntheme to the HA frontend, and on Android it exposes a Fully Kiosk Browser–compatible REST API so\nHA can control the device (screen on/off, volume, TTS announcements, camera snapshots, and more)."
  },
  {
    "id": "features:can-dashie-show-camera-video-feeds",
    "file": "features.md",
    "title": "Can Dashie show camera / video feeds?",
    "topic": "features",
    "status": "beta",
    "page": "video-feeds",
    "action": "open_settings_page(video-feeds)",
    "body": "Newer feature — Android/Home-Assistant kiosk devices, and may not be on your plan yet. On those\ndevices Dashie can play camera streams natively (smoother and lighter than in the HA web view):\ncameras can show as feed cards, pop up automatically on a motion or doorbell trigger (up to a 2×2\ngrid for several at once), go full-screen, and — with Frigate — play back events. Set feeds up\nunder **Settings → Video Feeds**."
  },
  {
    "id": "features:can-i-add-my-own-photos-from-my-phone",
    "file": "features.md",
    "title": "Can I add my own photos from my phone?",
    "topic": "features",
    "status": "beta",
    "page": null,
    "action": null,
    "body": "Newer feature — may not be on your plan yet. You can upload photos to Dashie's slideshow straight\nfrom your phone: the TV shows a QR code and a short pairing code, you open the link on your phone,\nand the photos you upload appear in the slideshow — no full sign-in needed. Photos can be kept in\nDashie's own storage or in your Google Drive."
  },
  {
    "id": "features:can-dashie-remind-me-about-things-scheduled-reminders",
    "file": "features.md",
    "title": "Can Dashie remind me about things? (scheduled reminders)",
    "topic": "features",
    "status": "beta",
    "page": null,
    "action": null,
    "body": "Newer feature — may not be on your plan yet. You can say \"Hey Dashie, remind me to take out the\ntrash in 30 minutes.\" Dashie sets a reminder, confirms it out loud, and when it's time a reminder\npops up on screen with a chime and a spoken message. This is different from a timer (a countdown)\n— a reminder is tied to a message and a time."
  },
  {
    "id": "overview:what-is-dashie",
    "file": "overview.md",
    "title": "What is Dashie?",
    "topic": "overview",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie is a smart home dashboard for families. It runs on wall-mounted TVs, tablets, and in\nany web browser, and turns a screen into a shared family hub: calendar, photos, weather, a\nclock, chores and rewards, plus a \"Hey Dashie\" voice assistant. On Android it can also act as\na dedicated Home Assistant kiosk display. Think of it as the always-on screen in the kitchen or\nhallway that keeps the whole household on the same page."
  },
  {
    "id": "overview:what-can-dashie-do-what-are-the-main-features",
    "file": "overview.md",
    "title": "What can Dashie do? / What are the main features?",
    "topic": "overview",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "The headline features are: a customizable widget dashboard (calendar, photos, weather, clock,\nchores, rewards); a \"Hey Dashie\" voice assistant for hands-free questions and control; family\ncoordination with chores and a points-based rewards system; a photo screensaver; timers; and\nHome Assistant integration for smart-home control. Ask \"how do I…\" about any of these and Dashie\ncan walk you through it."
  },
  {
    "id": "overview:what-are-the-two-modes-kiosk-and-full",
    "file": "overview.md",
    "title": "What are the two modes — kiosk and full?",
    "topic": "overview",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie has two modes. **Kiosk mode** (no login) is a Home Assistant kiosk display — great for\nwall-mounted tablets showing an HA dashboard, with an optional voice add-on. **Full mode**\n(signed in with a Dashie account) is the whole family dashboard: calendar, photos, chores,\nrewards, and the AI voice assistant. You can switch between them anytime — signing in from kiosk\nmode opens the full dashboard, and signing out returns to the kiosk."
  },
  {
    "id": "overview:what-devices-and-platforms-does-dashie-run-on",
    "file": "overview.md",
    "title": "What devices and platforms does Dashie run on?",
    "topic": "overview",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Dashie runs on TV/display devices (Google TV / ONN sticks, Fire TV, Mioio Android displays),\nany modern desktop browser at dashieapp.com, phones and tablets (responsive web plus a native\niOS app), and Android as a single app that supports both kiosk and full modes. The same account\nand settings follow you across devices."
  },
  {
    "id": "overview:do-i-need-an-account",
    "file": "overview.md",
    "title": "Do I need an account?",
    "topic": "overview",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Kiosk mode (the Home Assistant display) needs no account. The full family dashboard — calendar,\nphotos, chores, rewards, and the AI voice assistant — requires a Dashie account, which you create\nby signing in with Google."
  },
  {
    "id": "overview:how-do-i-sign-in-or-create-an-account",
    "file": "overview.md",
    "title": "How do I sign in or create an account?",
    "topic": "overview",
    "status": "ga",
    "page": "account",
    "action": "open_settings_page(account)",
    "body": "Open **Settings → Account** and choose sign in. On a desktop or phone you sign in with Google.\nOn a TV, Dashie shows a QR code (device flow) — scan it with your phone to link the TV to your\naccount without typing. Once signed in, the dashboard switches to full mode automatically."
  },
  {
    "id": "settings-map:where-do-i-change-the-theme-turn-on-dark-mode",
    "file": "settings-map.md",
    "title": "Where do I change the theme / turn on dark mode?",
    "topic": "settings",
    "status": "ga",
    "page": "display-manage-themes",
    "action": "open_settings_page(display-manage-themes)",
    "body": "Open **Settings → Display → Manage Themes**. There you can switch between Light and Dark mode and\npick seasonal overlays (Halloween, Christmas). You can also just say \"switch to dark mode\" or\n\"turn on the light theme.\""
  },
  {
    "id": "settings-map:where-are-the-display-settings-clock-format-dashboard-zoom-s",
    "file": "settings-map.md",
    "title": "Where are the display settings — clock format, dashboard zoom, screen-off?",
    "topic": "settings",
    "status": "ga",
    "page": "display",
    "action": "open_settings_page(display)",
    "body": "Open **Settings → Display**. This is where you set the 24-hour vs 12-hour clock, the dashboard\nzoom / display size, dark mode, and screen-off behavior."
  },
  {
    "id": "settings-map:how-do-i-set-up-sleep-and-wake-times",
    "file": "settings-map.md",
    "title": "How do I set up sleep and wake times?",
    "topic": "settings",
    "status": "ga",
    "page": "display-sleep",
    "action": "open_settings_page(display-sleep)",
    "body": "Open **Settings → Display → Sleep/Wake**. You can schedule when the screen sleeps and wakes, set\nan inactivity timeout, and choose the wake behavior."
  },
  {
    "id": "settings-map:where-do-i-change-the-screensaver-photo-source-and-timing",
    "file": "settings-map.md",
    "title": "Where do I change the screensaver — photo source and timing?",
    "topic": "settings",
    "status": "ga",
    "page": "display-screensaver",
    "action": "open_settings_page(display-screensaver)",
    "body": "Open **Settings → Display → Screensaver**. Choose the photo source (Home Assistant media, a local\nfolder, Immich, or Google Photos), how long each photo shows, the transition, dim brightness, and\nwhether photo metadata is displayed."
  },
  {
    "id": "settings-map:how-do-i-add-or-remove-a-calendar",
    "file": "settings-map.md",
    "title": "How do I add or remove a calendar?",
    "topic": "settings",
    "status": "ga",
    "page": "calendar-add",
    "action": "open_settings_page(calendar-add)",
    "body": "Open **Settings → Calendar**, then **Add calendar** to connect a Google or Outlook account, or\n**Remove** to disconnect one. Use **Select calendars** to choose which of your connected\ncalendars are visible on the dashboard. (To just pick which calendars show, use\nSettings → Calendar → Select calendars.)"
  },
  {
    "id": "settings-map:how-do-i-choose-which-calendars-are-visible",
    "file": "settings-map.md",
    "title": "How do I choose which calendars are visible?",
    "topic": "settings",
    "status": "ga",
    "page": "calendar-select",
    "action": "open_settings_page(calendar-select)",
    "body": "Open **Settings → Calendar → Select calendars** and toggle each calendar on or off. Only the ones\nyou enable appear on the dashboard and are read by the voice assistant."
  },
  {
    "id": "settings-map:where-are-the-voice-and-ai-settings",
    "file": "settings-map.md",
    "title": "Where are the voice and AI settings?",
    "topic": "settings",
    "status": "ga",
    "page": "voice",
    "action": "open_settings_page(voice)",
    "body": "Open **Settings → Voice & AI**. This is where you turn voice on or off, enable the wake word,\nchoose the voice pipeline, and pick the AI model. Sub-screens let you pick the spoken voice\n(Voice → Select voice), the AI model (Voice → AI model), and the wake word."
  },
  {
    "id": "settings-map:how-do-i-change-the-ai-voice-the-voice-dashie-speaks-in",
    "file": "settings-map.md",
    "title": "How do I change the AI voice (the voice Dashie speaks in)?",
    "topic": "settings",
    "status": "ga",
    "page": "voice-select",
    "action": "open_settings_page(voice-select)",
    "body": "Open **Settings → Voice & AI → Select voice** and pick a voice. You can also say \"change your\nvoice to <name>.\""
  },
  {
    "id": "settings-map:how-do-i-change-which-ai-model-dashie-uses",
    "file": "settings-map.md",
    "title": "How do I change which AI model Dashie uses?",
    "topic": "settings",
    "status": "ga",
    "page": "voice-ai-model-select",
    "action": "open_settings_page(voice-ai-model-select)",
    "body": "Open **Settings → Voice & AI → AI model** and choose the provider/model (Claude, OpenAI, or\nGemini)."
  },
  {
    "id": "settings-map:where-do-i-manage-family-members-roles-and-invitations",
    "file": "settings-map.md",
    "title": "Where do I manage family members, roles, and invitations?",
    "topic": "settings",
    "status": "ga",
    "page": "family",
    "action": "open_settings_page(family)",
    "body": "Open **Settings → Family**. Add or edit members, set their role (Owner, Parent, or Member), pick\nmember colors, and send invitations so others can join the family."
  },
  {
    "id": "settings-map:where-are-the-chores-and-rewards-settings",
    "file": "settings-map.md",
    "title": "Where are the chores and rewards settings?",
    "topic": "settings",
    "status": "ga",
    "page": "chores-rewards",
    "action": "open_settings_page(chores-rewards)",
    "body": "Open **Settings → Chores & Rewards** to create and manage chores (points, assignment, time of\nday, icons) and the rewards catalog (point costs, approval)."
  },
  {
    "id": "settings-map:where-do-i-connect-photos-dropbox-albums-slideshow-timing",
    "file": "settings-map.md",
    "title": "Where do I connect photos (Dropbox / albums / slideshow timing)?",
    "topic": "settings",
    "status": "ga",
    "page": "photos",
    "action": "open_settings_page(photos)",
    "body": "Open **Settings → Photos** to connect Dropbox, choose albums, and set slideshow timing for the\nPhotos widget. (The screensaver's photo source is set separately under Display → Screensaver.)"
  },
  {
    "id": "settings-map:where-do-i-set-up-home-assistant-dashboard-url-token",
    "file": "settings-map.md",
    "title": "Where do I set up Home Assistant (dashboard URL, token)?",
    "topic": "settings",
    "status": "ga",
    "page": "home-assistant",
    "action": "open_settings_page(home-assistant)",
    "body": "Open **Settings → Home Assistant**. Set the dashboard URL, hide/show the HA sidebar and tabs,\nconfigure the API, and paste your access token. (This page is available in kiosk mode.)"
  },
  {
    "id": "settings-map:where-do-i-configure-family-gps-locations",
    "file": "settings-map.md",
    "title": "Where do I configure family GPS locations?",
    "topic": "settings",
    "status": "ga",
    "page": "locations",
    "action": "open_settings_page(locations)",
    "body": "Open **Settings → Locations** to configure family member GPS/location tracking."
  },
  {
    "id": "settings-map:where-do-i-set-up-music",
    "file": "settings-map.md",
    "title": "Where do I set up music?",
    "topic": "settings",
    "status": "ga",
    "page": "music",
    "action": "open_settings_page(music)",
    "body": "Open **Settings → Music** to pick the Home Assistant media_player entity and configure volume\nsync for the music overlay."
  },
  {
    "id": "settings-map:where-do-i-set-up-camera-video-feeds",
    "file": "settings-map.md",
    "title": "Where do I set up camera / video feeds?",
    "topic": "settings",
    "status": "beta",
    "page": "video-feeds",
    "action": "open_settings_page(video-feeds)",
    "body": "Newer feature — Android/Home-Assistant kiosk devices, may not be on your plan yet. Open\n**Settings → Video Feeds** to add camera streams, set the feed size, and control motion/doorbell\nalert behavior. Basic camera options are also under **Settings → Camera**."
  },
  {
    "id": "settings-map:where-are-account-settings-pin-zip-code-sign-out",
    "file": "settings-map.md",
    "title": "Where are account settings — PIN, zip code, sign out?",
    "topic": "settings",
    "status": "ga",
    "page": "account",
    "action": "open_settings_page(account)",
    "body": "Open **Settings → Account** for PIN protection, your zip code, and sign in / sign out. On a locked\nkiosk, opening Settings or the Control Center prompts for the PIN (with a short grace period after\nyou enter it correctly)."
  },
  {
    "id": "settings-map:where-do-i-find-device-info-cache-and-diagnostics",
    "file": "settings-map.md",
    "title": "Where do I find device info, cache, and diagnostics?",
    "topic": "settings",
    "status": "ga",
    "page": "system",
    "action": "open_settings_page(system)",
    "body": "Open **Settings → System** for device information, clearing the cache, sending diagnostics, and a\nshortcut to Android's own settings."
  },
  {
    "id": "settings-map:where-are-the-advanced-settings",
    "file": "settings-map.md",
    "title": "Where are the advanced settings?",
    "topic": "settings",
    "status": "ga",
    "page": "advanced",
    "action": "open_settings_page(advanced)",
    "body": "Open **Settings → Advanced** for return-to-home behavior, periodic refresh, performance and\nmemory management, and data-sharing options."
  },
  {
    "id": "troubleshooting:my-screen-is-black-blank",
    "file": "troubleshooting.md",
    "title": "My screen is black / blank",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "display-screensaver",
    "action": "open_settings_page(display-screensaver)",
    "body": "A black screen is usually the screensaver or a scheduled sleep. Tap the screen or press a remote\nbutton to wake it. If it stays black, check **Settings → Display → Sleep/Wake** for a sleep\nschedule or inactivity timeout, and **Settings → Display → Screensaver** for the dim setting. If\nthe screen is on but the dashboard didn't come back, a reload usually fixes it."
  },
  {
    "id": "troubleshooting:my-calendar-events-aren-t-showing-up",
    "file": "troubleshooting.md",
    "title": "My calendar events aren't showing up",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "calendar-select",
    "action": "open_settings_page(calendar-select)",
    "body": "First check **Settings → Calendar → Select calendars** and make sure the calendar is toggled on —\nonly enabled calendars appear. If the account is missing entirely, re-add it under\nSettings → Calendar → Add calendar. Newly added events can take a short while to sync; a refresh\nspeeds it up."
  },
  {
    "id": "troubleshooting:the-voice-assistant-isn-t-responding-to-hey-dashie",
    "file": "troubleshooting.md",
    "title": "The voice assistant isn't responding to \"Hey Dashie\"",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "voice",
    "action": "open_settings_page(voice)",
    "body": "Check **Settings → Voice & AI**: make sure voice and the wake word are enabled and the microphone\nisn't muted. The wake word needs microphone permission and works on supported devices (Android/TV\nwith the voice feature). If the wake word won't trigger, you can always tap the microphone button\nto talk instead. Reducing background noise helps detection."
  },
  {
    "id": "troubleshooting:the-dashboard-is-frozen-or-won-t-load",
    "file": "troubleshooting.md",
    "title": "The dashboard is frozen or won't load",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "system",
    "action": "open_settings_page(system)",
    "body": "Try reloading the dashboard first. If it's still stuck, clear the cache under\n**Settings → System**, then reload. On Android, force-stopping and reopening the app clears the\nin-memory state. If a specific widget is the problem, removing and re-adding it can help."
  },
  {
    "id": "troubleshooting:photos-aren-t-showing-in-the-screensaver-or-widget",
    "file": "troubleshooting.md",
    "title": "Photos aren't showing in the screensaver or widget",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "display-screensaver",
    "action": "open_settings_page(display-screensaver)",
    "body": "Confirm the photo source is set and reachable under **Settings → Display → Screensaver** (for the\nscreensaver) or **Settings → Photos** (for the widget and Dropbox). If the source is Google\nPhotos, Immich, Dropbox, or HA media, make sure that connection is still authorized. An empty\nalbum or an expired connection shows no photos."
  },
  {
    "id": "troubleshooting:home-assistant-isn-t-connecting-or-the-dashboard-is-blank",
    "file": "troubleshooting.md",
    "title": "Home Assistant isn't connecting or the dashboard is blank",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "home-assistant",
    "action": "open_settings_page(home-assistant)",
    "body": "Check **Settings → Home Assistant**: verify the dashboard URL and that the access token is still\nvalid. If HA is on your local network, the device needs to be on the same network. A 404 or blank\nHA iframe usually means the URL or token needs updating."
  },
  {
    "id": "troubleshooting:the-screen-keeps-going-to-sleep-too-soon-or-won-t-sleep",
    "file": "troubleshooting.md",
    "title": "The screen keeps going to sleep too soon (or won't sleep)",
    "topic": "troubleshooting",
    "status": "ga",
    "page": "display-sleep",
    "action": "open_settings_page(display-sleep)",
    "body": "Adjust the schedule and inactivity timeout under **Settings → Display → Sleep/Wake**. If it sleeps\ntoo soon, lengthen the inactivity timeout; if it never sleeps, check that a sleep schedule is set."
  },
  {
    "id": "troubleshooting:how-do-i-report-a-bug-or-something-that-s-broken",
    "file": "troubleshooting.md",
    "title": "How do I report a bug or something that's broken?",
    "topic": "troubleshooting",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "If a fix here doesn't solve it, email the Dashie team at **support@dashieapp.com** with a\ndescription of the problem. On Android you can also send diagnostics from **Settings → System**,\nwhich gives the team device logs to look into it. (Voice-driven \"tell the team X\" support\nsubmission is a planned addition.)"
  },
  {
    "id": "voice-capabilities:what-can-you-do-what-can-i-ask-you",
    "file": "voice-capabilities.md",
    "title": "What can you do? / What can I ask you?",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "You can ask me about your family calendar, the weather, and sports scores; control your Home\nAssistant smart home; set and manage timers; complete chores; check where family members are and\ntravel time to events; change the theme or my voice; and ask how Dashie works — where a setting\nis, how to do something, or how to fix a problem. Just talk naturally, by voice or by typing."
  },
  {
    "id": "voice-capabilities:ask-about-the-calendar",
    "file": "voice-capabilities.md",
    "title": "Ask about the calendar",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Ask things like \"what's on the calendar today?\", \"do I have anything this weekend?\", \"when is the\nnext soccer game?\", or \"what time is Mom's appointment?\" I read from your real merged calendar,\nincluding who each event belongs to."
  },
  {
    "id": "voice-capabilities:ask-about-the-weather",
    "file": "voice-capabilities.md",
    "title": "Ask about the weather",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Ask \"what's the weather?\", \"will it rain today?\", \"how's the forecast this weekend?\", or the\nweather for a specific place. I use your family's home location unless you name somewhere else."
  },
  {
    "id": "voice-capabilities:control-the-smart-home-home-assistant",
    "file": "voice-capabilities.md",
    "title": "Control the smart home (Home Assistant)",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Say things like \"turn on the kitchen lights,\" \"close the garage,\" \"set the thermostat to 70,\" or\n\"is the garage door open?\" I pass these to Home Assistant, including multi-device commands."
  },
  {
    "id": "voice-capabilities:set-timers",
    "file": "voice-capabilities.md",
    "title": "Set timers",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Say \"set a 5 minute timer,\" \"how much time is left?\", \"pause the timer,\" or \"cancel it.\" You can\nrun up to three timers at once."
  },
  {
    "id": "voice-capabilities:chores-and-rewards",
    "file": "voice-capabilities.md",
    "title": "Chores and rewards",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Say \"mark dishes as done\" or \"I finished taking out the trash\" to complete a chore, or ask \"what\nchores are left?\" You can also ask about rewards you can redeem."
  },
  {
    "id": "voice-capabilities:change-the-theme-or-my-voice",
    "file": "voice-capabilities.md",
    "title": "Change the theme or my voice",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Say \"switch to dark mode,\" \"turn on the light theme,\" or \"change your voice.\" For anything else in\nsettings, ask me where it is and I'll point you to the right page."
  },
  {
    "id": "voice-capabilities:change-my-personality",
    "file": "voice-capabilities.md",
    "title": "Change my personality",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Ask \"what personalities do you have?\" to hear the options, then say \"switch to the princess\npersonality,\" \"be a pirate,\" or \"talk like a wizard\" to change me. Each personality has its own\nvoice, and the change applies to this device only — so a different Dashie in another room keeps\nits own. Say \"go back to normal\" to return to the default."
  },
  {
    "id": "voice-capabilities:sports-scores",
    "file": "voice-capabilities.md",
    "title": "Sports scores",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Ask \"did the <team> win?\", \"what's the score?\", or \"when do the <team> play next?\" I look up live\nscores and schedules for a specific team or league."
  },
  {
    "id": "voice-capabilities:ask-about-dashie-itself",
    "file": "voice-capabilities.md",
    "title": "Ask about Dashie itself",
    "topic": "voice",
    "status": "ga",
    "page": null,
    "action": null,
    "body": "Ask \"how do I add a calendar?\", \"where's the dark mode setting?\", \"why is my screen black?\", or\n\"what is Dashie?\" I answer from Dashie's own knowledge rather than guessing or searching the web."
  },
  {
    "id": "voice-capabilities:set-reminders",
    "file": "voice-capabilities.md",
    "title": "Set reminders",
    "topic": "voice",
    "status": "beta",
    "page": null,
    "action": null,
    "body": "Newer feature — may not be on your plan yet. Say \"remind me to take out the trash in 30 minutes\"\nand I'll set a reminder and confirm it; when it's time a reminder pops up with a chime and a spoken\nmessage. Reminders are for a message at a time; timers are plain countdowns."
  },
  {
    "id": "voice-capabilities:have-a-back-and-forth-conversation",
    "file": "voice-capabilities.md",
    "title": "Have a back-and-forth conversation",
    "topic": "voice",
    "status": "beta",
    "page": "voice",
    "action": "open_settings_page(voice)",
    "body": "Newer feature — opt-in and may not be on your plan yet. If you turn on conversation mode in\n**Settings → Voice & AI**, you can say \"Hey Dashie, conversation mode\" to start a continuous\nback-and-forth — I keep listening between turns and you can interrupt me, until you say \"that's\nall\" or go quiet. Normally each request just starts with \"Hey Dashie.\""
  }
];
