/* ============================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND
   ------------------------------------------------------------
   Source of truth:
     js/ai/prompts/prompt-builder.js
   Generated by:
     dashieapp_staging/scripts/bundle-ai-prompts.js
   To update: edit the source(s) above and run
       node scripts/bundle-ai-prompts.js
   (or just release the add-on — scripts/release.sh runs this first).
   ============================================================ */

(function () {
    // Resolved at first use so PersonalityPromptBuilder load order
    // is forgiving (its bundle just needs to be loaded before any
    // buildPrompt call, not before this IIFE runs).
    function buildPersonalityPrompt(p) {
        return window.PersonalityPromptBuilder.buildPersonalityPrompt(p);
    }

    /**
     * Prompt Builder Utility
     *
     * Loads and assembles AI prompts from markdown templates.
     * Templates use {{PLACEHOLDER}} syntax for variable substitution.
     */

    // Cache for loaded templates
    const templateCache = new Map();

    /**
     * Pre-injected templates, set by the IIFE-bundled Console build at boot
     * (from window.AiPromptTemplates). When set, loadTemplate skips fetch
     * and serves from this map — the Console runs in HA Ingress and can't
     * fetch /js/ai/prompts/* the way the webapp can. The webapp leaves this
     * null and uses the fetch path as before.
     */
    let injectedTemplates = null;

    /** Set the in-memory template source. Console-only — the bundler calls
     *  this at IIFE init with window.AiPromptTemplates. */
    function injectTemplates(map) {
      injectedTemplates = map;
    }

    /**
     * Load a template file (with caching)
     * @param {string} templatePath - Path relative to prompts directory
     * @returns {Promise<string>} Template content
     */
    async function loadTemplate(templatePath) {
      if (injectedTemplates) {
        const t = injectedTemplates[templatePath];
        if (t != null) return t;
        throw new Error(`Template not in injected map: ${templatePath}`);
      }
      if (templateCache.has(templatePath)) {
        return templateCache.get(templatePath);
      }

      const fullPath = `/js/ai/prompts/${templatePath}`;

      try {
        const response = await fetch(fullPath);

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        const content = await response.text();
        templateCache.set(templatePath, content);

        return content;
      } catch (error) {

        throw new Error(`Failed to load template: ${templatePath}`);
      }
    }

    /**
     * Fill template placeholders with values
     * @param {string} template - Template string with {{PLACEHOLDER}} syntax
     * @param {Object} values - Key-value pairs for replacement
     * @returns {string} Filled template
     */
    function fillTemplate(template, values) {
      return template.replace(/\{\{(\w+)\}\}/g, (match, key) => {
        if (values[key] !== undefined && values[key] !== null) {
          return values[key];
        }
        // Leave placeholder if no value provided

        return '';
      });
    }

    /**
     * Generate tool list for prompt based on available features
     * Only includes tools that are available on the current platform
     *
     * @returns {string} Formatted tool list for prompt
     */
    function generateAvailableToolsList() {
        return window.AiPromptTemplates.AVAILABLE_TOOLS_LIST;
    }

    /**
     * Map a Preferences locale code (e.g. 'es-ES', 'pt-BR') to a plain-English
     * language name the AI understands. The 15 supported codes mirror Kotlin's
     * PreferencesPageSchema.languageOptions() — keep in sync if either changes.
     */
    function languageNameFor(code) {
      return {
        'en-US': 'English',
        'en-GB': 'British English',
        'es-ES': 'Spanish',
        'es-US': 'Spanish',
        'fr-FR': 'French',
        'de-DE': 'German',
        'it-IT': 'Italian',
        'pt-BR': 'Brazilian Portuguese',
        'nl-NL': 'Dutch',
        'pl-PL': 'Polish',
        'hi-IN': 'Hindi',
        'ja-JP': 'Japanese',
        'ko-KR': 'Korean',
        'zh-CN': 'Simplified Chinese',
      }[code] || code;
    }

    /**
     * Format current date and time for display
     * Uses configured timezone to show correct time on devices with wrong system clocks
     * @returns {string} Formatted date/time string
     */
    function formatDateTime() {
      const now = new Date();
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;

      return now.toLocaleDateString('en-US', {
        timeZone: timezone,
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      }) + ', ' + now.toLocaleTimeString('en-US', {
        timeZone: timezone,
        hour: 'numeric',
        minute: '2-digit',
        hour12: true
      });
    }

    /**
     * Build values for inquiry-specific templates
     * @param {string} inquiryType - Type of inquiry
     * @param {Object} data - Retrieved data
     * @param {Object} baseValues - Base template values
     * @returns {Object} Values for inquiry template
     */
    function buildInquiryValues(inquiryType, data, baseValues) {
      switch (inquiryType) {
        case 'calendar-events':
          return {
            ...baseValues,
            MEMBER_NAME: data.member_details?.nickname || data.member_details?.name || 'the family',
            TAGS_CONTEXT: data.metadata?.tag_filter
              ? ` and events related to ${data.metadata.tag_filter.join(', ')}`
              : '',
            TAGS_FILTER_NOTE: data.metadata?.tag_filter
              ? ` (filtered by: ${data.metadata.tag_filter.join(', ')})`
              : '',
            MEMBER_DETAILS: data.member_details
              ? JSON.stringify(data.member_details, null, 2)
              : 'No specific member filter applied.',
            CALENDAR_DATA: JSON.stringify(data, null, 2)
          };

        case 'family-members':
          return {
            ...baseValues,
            FAMILY_DATA: JSON.stringify(data, null, 2)
          };

        case 'web-search':
          return {
            ...baseValues,
            SEARCH_RESULTS: JSON.stringify(data, null, 2)
          };

        case 'dashie-help':
          return {
            ...baseValues,
            DASHIE_HELP_DATA: JSON.stringify(data, null, 2)
          };

        case 'chores':
          return {
            ...baseValues,
            CHORES_DATA: JSON.stringify(data.chores, null, 2),
            FAMILY_MEMBERS: JSON.stringify(data.family_members, null, 2),
            TODAYS_COMPLETIONS: JSON.stringify(data.todays_completions, null, 2)
          };

        case 'rewards':
          return {
            ...baseValues,
            REWARDS_DATA: JSON.stringify(data.rewards, null, 2),
            FAMILY_MEMBERS: JSON.stringify(data.family_members, null, 2),
            RECENT_REDEMPTIONS: JSON.stringify(data.recent_redemptions, null, 2)
          };

        case 'location-events':
          return {
            ...baseValues,
            MEMBER_NAME: data.member_details?.nickname || data.member_details?.name || data.query?.member_name || 'unknown',
            LOCATION_NAME: data.query?.location_name || 'any location',
            TIMEFRAME: data.query?.timeframe || 'today',
            EVENT_TYPE: data.query?.event_type || 'all events',
            MEMBER_DETAILS: data.member_details
              ? JSON.stringify(data.member_details, null, 2)
              : 'Member not found or not specified.',
            LOCATION_EVENTS_DATA: JSON.stringify(data, null, 2)
          };

        case 'travel-time':
          return {
            ...baseValues,
            EVENT_TITLE: data.event?.title || data.event?.summary || 'Unknown event',
            EVENT_START_TIME: data.event?.startTime || data.timing?.eventStart || 'Unknown time',
            EVENT_LOCATION: data.event?.location || data.destination?.address || 'Unknown location',
            ORIGIN_ADDRESS: data.origin?.address || 'Home',
            EVENT_NOTES: data.event?.description || data.event?.notes || 'No notes',
            TRAVEL_TIME_DATA: JSON.stringify(data, null, 2)
          };

        case 'family-locations':
          return {
            ...baseValues,
            MEMBER_NAME: data.member?.nickname || data.member?.name || data.query?.member_name || 'unknown',
            MEMBER_DETAILS: data.member
              ? JSON.stringify(data.member, null, 2)
              : 'Member not found.',
            LOCATION_DATA: JSON.stringify(data, null, 2)
          };

        case 'weather':
          return {
            ...baseValues,
            LOCATION_CITY: data.location?.city || 'Unknown',
            LOCATION_STATE: data.location?.state || '',
            WEATHER_DATA: JSON.stringify(data, null, 2)
          };

        case 'home-assistant':
          return {
            ...baseValues,
            HA_ENTITIES: JSON.stringify(data.entities || [], null, 2),
            HA_ENTITIES_BY_DOMAIN: JSON.stringify(data.entities_by_domain || {}, null, 2),
            COMMAND_HINT: data.command_hint || baseValues.USER_REQUEST
          };

        default:
          return baseValues;
      }
    }

    /**
     * Build complete prompt for AI
     * @param {Object} options
     * @param {string} options.userRequest - User's voice/text input
     * @param {string} options.inquiryType - 'calendar-events' | 'family-members' | 'web-search' | null
     * @param {Object} options.retrievedData - Data from info request (if any)
     * @param {Object} options.context - Additional context values (including personalityMode)
     * @returns {Promise<string>} Complete prompt
     */
    async function buildPrompt({ userRequest, inquiryType, retrievedData, context = {} }) {

      const dateTime = formatDateTime();

      // Check for personality mode (e.g., 'santa')
      // Custom personality config takes precedence over built-in modes
      let personalityConfig = null;

      if (context.customPersonalityConfig) {
        // Build prompt from structured personality fields
        const { responsePrefix, responseSuffix } = buildPersonalityPrompt(context.customPersonalityConfig);
        personalityConfig = {
          name: context.customPersonalityConfig.name,
          responsePrefix,
          responseSuffix
        };

      }

      // Generate available tools list for prompt (platform-aware)
      const availableToolsList = generateAvailableToolsList();

      // Language: resolve from account-wide Preferences. 'system' or absent
      // means follow the model's default — we omit the instruction entirely
      // so we don't waste tokens on a no-op line.
      //
      // Source priority:
      //   1. context.language (Console passes from its cached user_settings)
      //   2. window.settingsStore (webapp dashboard hydrates this at boot)
      //   3. 'system' (no instruction emitted)
      const languageCode = context.language
        || (typeof window !== 'undefined' && window.settingsStore?.get?.('general.language'))
        || 'system';
      const languageInstruction = (languageCode && languageCode !== 'system')
        ? `Respond in ${languageNameFor(languageCode)}.`
        : '';

      // Base values for all templates
      const baseValues = {
        DATE_TIME: dateTime,
        USER_REQUEST: userRequest,
        CHAT_HISTORY: context.chatHistory || '',  // Empty for now, implement later
        AVAILABLE_TOOLS_LIST: availableToolsList,
        LANGUAGE_INSTRUCTION: languageInstruction,
        ...context
      };

      // Load and fill base context
      const baseTemplate = await loadTemplate('base-context.md');
      let prompt = fillTemplate(baseTemplate, baseValues);

      // Add personality prefix if applicable (prepend to existing prompt)
      if (personalityConfig) {
        const personalityPrefix = personalityConfig.responsePrefix || '';
        prompt = personalityPrefix + '\n\n' + prompt;

      }

      // Add inquiry-specific context if we have retrieved data
      if (inquiryType && retrievedData) {
        try {
          const inquiryTemplate = await loadTemplate(`inquiries/${inquiryType}.md`);
          const inquiryValues = buildInquiryValues(inquiryType, retrievedData, baseValues);
          prompt += '\n\n' + fillTemplate(inquiryTemplate, inquiryValues);
        } catch (error) {

        }

        // With retrieved data, use the full response format (includes all display flags)
        const responseFormat = await loadTemplate('response-format.md');
        prompt += '\n\n' + fillTemplate(responseFormat, baseValues);
      } else {
        // Initial request (no data yet) - use slim format focused on tool selection.
        // fillTemplate is essential here — response-format-initial.md references
        // {{AVAILABLE_TOOLS_LIST}}, and without substitution the AI sees the raw
        // placeholder and can't pick a tool. (Bug hidden until LANGUAGE_INSTRUCTION
        // landed on base-context.md — same surface, easier to spot.)
        const responseFormat = await loadTemplate('response-format-initial.md');
        prompt += '\n\n' + fillTemplate(responseFormat, baseValues);
      }

      // Add personality suffix if applicable (append after response format)
      if (personalityConfig && personalityConfig.responseSuffix) {
        prompt += personalityConfig.responseSuffix;
      }

      return prompt;
    }

    /**
     * Clear template cache (for development/testing)
     */
    function clearTemplateCache() {
      templateCache.clear();

    }

    /**
     * Preload all templates (optional, for faster first queries)
     */
    async function preloadTemplates() {
      const templatePaths = [
        'base-context.md',
        'response-format.md',
        'response-format-initial.md',
        'inquiries/calendar-events.md',
        'inquiries/family-members.md',
        'inquiries/web-search.md',
        'inquiries/chores.md',
        'inquiries/rewards.md',
        'inquiries/location-events.md',
        'inquiries/travel-time.md',
        'inquiries/family-locations.md',
        'inquiries/weather.md',
        'inquiries/home-assistant.md'
      ];

      await Promise.all(templatePaths.map(path =>
        loadTemplate(path).catch(err => {

        })
      ));

    }

    // Pre-inject templates so loadTemplate() never needs to fetch.
    // Paths match the webapp's loadTemplate(`inquiries/${type}.md`) calls.
    (function initTemplates() {
        const T = window.AiPromptTemplates;
        injectTemplates({
            'base-context.md':              T.BASE_CONTEXT,
            'response-format.md':           T.RESPONSE_FORMAT_FULL,
            'response-format-initial.md':   T.RESPONSE_FORMAT_INITIAL,
            'inquiries/home-assistant.md':  T.INQUIRY_HOME_ASSISTANT,
            'inquiries/web-search.md':      T.INQUIRY_WEB_SEARCH,
            'inquiries/calendar-events.md': T.INQUIRY_CALENDAR_EVENTS,
            'inquiries/family-members.md':  T.INQUIRY_FAMILY_MEMBERS,
            'inquiries/chores.md':          T.INQUIRY_CHORES,
            'inquiries/rewards.md':         T.INQUIRY_REWARDS,
            'inquiries/location-events.md': T.INQUIRY_LOCATION_EVENTS,
            'inquiries/travel-time.md':     T.INQUIRY_TRAVEL_TIME,
            'inquiries/family-locations.md':T.INQUIRY_FAMILY_LOCATIONS,
            'inquiries/weather.md':         T.INQUIRY_WEATHER,
        });
    })();

    window.PromptBuilder = {
        buildPrompt,
        clearTemplateCache,
    };
})();
