/* ============================================================
   AUTO-GENERATED — DO NOT EDIT BY HAND
   ------------------------------------------------------------
   Source of truth:
     js/ai/ai-models-catalog.js
   Generated by:
     dashieapp_staging/scripts/bundle-ai-prompts.js
   To update: edit the source(s) above and run
       node scripts/bundle-ai-prompts.js
   (or just release the add-on — scripts/release.sh runs this first).
   ============================================================ */


export const MODEL_LABELS: Record<string, string> = {
  "claude-sonnet-4-6": "Claude Sonnet 4.6",
  "claude-opus-4-8": "Claude Opus 4.8",
  "claude-haiku-4-5": "Claude Haiku 4.5",
  "gpt-5.5": "GPT-5.5",
  "gpt-5.4": "GPT-5.4",
  "gpt-5.4-mini": "GPT-5.4 Mini",
  "gpt-5.4-nano": "GPT-5.4 Nano",
  "gemini-3.5-flash": "Gemini 3.5 Flash",
  "gemini-2.5-flash": "Gemini 2.5 Flash",
  "gemini-3.1-flash-lite": "Gemini 3.1 Flash Lite",
  "gemini-2.5-pro": "Gemini 2.5 Pro",
  "us.amazon.nova-2-lite-v1:0": "Amazon Nova 2 Lite",
  "us.amazon.nova-pro-v1:0": "Amazon Nova Pro",
  "us.amazon.nova-micro-v1:0": "Amazon Nova Micro"
};

/** Speakable name for a wire model id. Falls back to the id itself — an
 *  unknown id is better spoken awkwardly than turned into a blank sentence, and
 *  a miss here must never be the reason a user hears nothing. */
export function modelLabel(id: string | null | undefined): string {
  const key = String(id || '');
  return MODEL_LABELS[key] || key;
}
